# Generated by Django 3.0.1 on 2020-02-15 09:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('alias', models.CharField(max_length=500)),
                ('actual_name', models.CharField(max_length=500)),
                ('username', models.CharField(max_length=500)),
                ('password', models.CharField(max_length=100)),
                ('phone_number', models.CharField(max_length=100)),
                ('email_address', models.CharField(max_length=100)),
                ('gender', models.CharField(max_length=100)),
                ('nationality', models.CharField(max_length=100)),
                ('role', models.CharField(max_length=100)),
                ('nric', models.CharField(max_length=100)),
                ('photo', models.CharField(max_length=500)),
                ('status', models.CharField(max_length=100)),
                ('datetime_last_login', models.DateTimeField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='Vendor',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=500)),
                ('uen', models.CharField(max_length=500)),
                ('phone_number', models.CharField(max_length=100)),
                ('email_address', models.CharField(max_length=100)),
                ('contact_person', models.CharField(max_length=100)),
                ('billing_address', models.CharField(max_length=1000)),
                ('distribution_venue', models.CharField(max_length=500)),
                ('remarks', models.CharField(max_length=10000)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='Worker',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=500)),
                ('fin_number', models.CharField(max_length=100)),
                ('fin_previous', models.CharField(max_length=100)),
                ('date_worker_registered', models.DateTimeField()),
                ('date_of_birth', models.DateTimeField()),
                ('when_first_arrive', models.CharField(max_length=100)),
                ('twid', models.CharField(max_length=100)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_for', models.CharField(max_length=100)),
                ('gender', models.CharField(max_length=100)),
                ('nationality', models.CharField(max_length=100)),
                ('nationality_more', models.CharField(max_length=100)),
                ('worker_flag', models.CharField(max_length=100)),
                ('path_current_facepic', models.CharField(max_length=100)),
                ('path_qr_code', models.CharField(max_length=100)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='adult.User')),
            ],
        ),
        migrations.AddField(
            model_name='user',
            name='vendor_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='adult.Vendor'),
        ),
    ]
