# Generated by Django 3.0.1 on 2020-02-16 12:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('adult', '0002_field_table'),
    ]

    operations = [
        migrations.RenameField(
            model_name='field',
            old_name='table_id',
            new_name='table',
        ),
        migrations.RenameField(
            model_name='user',
            old_name='vendor_id',
            new_name='vendor',
        ),
    ]
