# Generated by Django 3.0.1 on 2020-02-16 14:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('adult', '0004_permissionprivilege_role'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='photo',
            field=models.CharField(blank=True, max_length=500),
        ),
        migrations.AlterField(
            model_name='user',
            name='vendor',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to='adult.Vendor'),
        ),
        migrations.AlterField(
            model_name='vendor',
            name='billing_address',
            field=models.CharField(blank=True, max_length=1000),
        ),
        migrations.AlterField(
            model_name='vendor',
            name='distribution_venue',
            field=models.CharField(blank=True, max_length=500),
        ),
        migrations.AlterField(
            model_name='vendor',
            name='email_address',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='vendor',
            name='phone_number',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='vendor',
            name='remarks',
            field=models.CharField(blank=True, max_length=10000),
        ),
        migrations.AlterField(
            model_name='vendor',
            name='uen',
            field=models.CharField(blank=True, max_length=500),
        ),
        migrations.AlterField(
            model_name='worker',
            name='fin_number',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='worker',
            name='fin_previous',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='worker',
            name='nationality_more',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='worker',
            name='path_current_facepic',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='worker',
            name='when_first_arrive',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='worker',
            name='worker_flag',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
