# Generated by Django 3.0.1 on 2020-02-16 14:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('adult', '0006_auto_20200216_1406'),
    ]

    operations = [
        migrations.AlterField(
            model_name='worker',
            name='created_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='adult.User'),
        ),
    ]
