# Generated by Django 3.0.1 on 2020-02-16 14:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adult', '0009_auto_20200216_1415'),
    ]

    operations = [
        migrations.AlterField(
            model_name='worker',
            name='created_for',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
