# Generated by Django 3.0.1 on 2020-02-17 12:22

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('adult', '0010_auto_20200216_1417'),
    ]

    operations = [
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('alias', models.CharField(max_length=500)),
                ('actual_name', models.CharField(max_length=500)),
                ('username', models.CharField(max_length=500)),
                ('password', models.CharField(max_length=100)),
                ('phone_number', models.CharField(max_length=100)),
                ('email_address', models.CharField(max_length=100)),
                ('gender', models.CharField(max_length=100)),
                ('nationality', models.CharField(max_length=100)),
                ('nric', models.CharField(max_length=100)),
                ('photo', models.CharField(blank=True, max_length=500)),
                ('status', models.CharField(max_length=100)),
                ('datetime_last_login', models.DateTimeField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('role', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='adult.Role')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('vendor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='adult.Vendor')),
            ],
        ),
        migrations.AlterField(
            model_name='worker',
            name='created_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.DeleteModel(
            name='User',
        ),
    ]
