# Generated by Django 3.0.1 on 2020-02-17 12:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('adult', '0011_auto_20200217_1222'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='email_address',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='password',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='username',
        ),
    ]
