# Generated by Django 3.0.1 on 2020-02-17 15:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adult', '0012_auto_20200217_1239'),
    ]

    operations = [
        migrations.AddField(
            model_name='field',
            name='dropdown',
            field=models.BooleanField(default=False),
        ),
    ]
