# Generated by Django 3.0.1 on 2020-02-21 17:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adult', '0014_fieldvalue'),
    ]

    operations = [
        migrations.AddField(
            model_name='field',
            name='url_string',
            field=models.CharField(blank=True, max_length=500),
        ),
    ]
