# Generated by Django 3.0.1 on 2020-02-21 17:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adult', '0016_auto_20200221_1724'),
    ]

    operations = [
        migrations.AddField(
            model_name='field',
            name='label',
            field=models.CharField(blank=True, max_length=500),
        ),
    ]
