# Generated by Django 3.0.1 on 2020-02-22 06:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adult', '0019_table_subsidiary_to'),
    ]

    operations = [
        migrations.AddField(
            model_name='twid',
            name='identifier',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
