# Generated by Django 3.0.1 on 2020-02-23 15:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adult', '0021_auto_20200222_0627'),
    ]

    operations = [
        migrations.AddField(
            model_name='table',
            name='database_table',
            field=models.CharField(blank=True, max_length=500),
        ),
    ]
