# Generated by Django 3.0.1 on 2020-02-23 16:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adult', '0023_nickname'),
    ]

    operations = [
        migrations.AddField(
            model_name='field',
            name='table_index',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
